<?php

namespace common\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "project".
 *
 * @property int $id
 * @property string $project_name
 * @property int $id_user
 * @property int $id_project_status
 *
 * @property Project $projectStatus
 * @property Project[] $projects
 * @property User $user
 */
class Project extends \yii\db\ActiveRecord
{
    const TIME_BEHAVIOR_NAME = 'timeBehavior';
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'project';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['project_name', 'id_project_status'], 'required'],
            [['id_user', 'id_project_status'], 'integer'],
            [['project_name'], 'string', 'max' => 50],
            [['id_project_status'], 'exist', 'skipOnError' => true, 'targetClass' => Project::className(), 'targetAttribute' => ['id_project_status' => 'id']],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_user' => 'id']],
        ];
    }
    public function behaviors()
    {
        return [
            self::TIME_BEHAVIOR_NAME => [
                'class' => \yii\behaviors\TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                    'value' => time(),
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'project_name' => 'Project Name',
            'id_user' => 'Id User',
            'id_project_status' => 'Id Project Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjectStatus()
    {
        return $this->hasOne(ProjectStatus::className(), ['id' => 'id_project_status']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjects()
    {
        return $this->hasMany(Project::className(), ['id_project_status' => 'id']);
    }

    public function getTask()
    {
        return $this->hasMany(Task::className(), ['id_task' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'id_user']);
    }

    public function beforeSave($insert)
    {
        $this->id_user = Yii::$app->user->identity->id;

        ChatLog::sendChat('Создан новый проект: '.$this->project_name);

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public static function getAktiveProjects(){

        return self::find()->where('id_project_status != :finished_status_id', [":finished_status_id" => ProjectStatus::FINISHED_ID])->all();
    }
}
